package com.eis.geoCalendar.database;

import android.content.Context;

import androidx.collection.ArrayMap;
import androidx.room.Database;
import androidx.room.Room;
import androidx.room.RoomDatabase;

import java.util.Map;

/**
 * Class representing the actual Room database in the memory.
 * This should not be instantiated outside of the package.
 * This database only handles writing and reading from memory, with no logic on what is stored,
 * as long as they are StringEntities.
 *
 * @author Riccardo De Zen.
 */
@Database(entities = StringEntity.class, version = 1)
public abstract class RoomEventDatabase extends RoomDatabase {

    //Map containing the active instances for this database.
    private static Map<String, RoomEventDatabase> activeInstances = new ArrayMap<>();

    /**
     * Method generated by Room to retrieve the appropriate access object to this Database.
     *
     * @return The appropriate {@link StringDao} for this database.
     */
    abstract StringDao access();

    /**
     * Only intended way to instantiate an instance of this Database.
     *
     * @param context The calling Context, needed for File directory.
     * @param name    The name for this Database. Will be used for the file.
     * @return An appropriately built instance for this Database.
     */
    static RoomEventDatabase getInstance(Context context, String name) {
        if (activeInstances.get(name) != null)
            return activeInstances.get(name);
        RoomEventDatabase newInstance = Room.databaseBuilder(context, RoomEventDatabase.class, name)
                .allowMainThreadQueries()
                .enableMultiInstanceInvalidation()
                .build();
        activeInstances.put(name, newInstance);
        return newInstance;
    }

    /**
     * Same as {@link RoomEventDatabase#getInstance(Context, String)} but the database is created
     * and stored directly in the device's memory, it can prove useful in some scenarios, but it
     * has been added for testing purposes only: Room databases cannot be physically instantiated
     * during Unit Testing.
     *
     * @param context The calling Context, needed for File directory.
     * @param name    The name for this Database.
     * @return An appropriately built instance for this Database.
     */
    static RoomEventDatabase getInMemoryInstance(Context context, String name) {
        if (activeInstances.get(name) != null)
            return activeInstances.get(name);
        RoomEventDatabase newInstance = Room.inMemoryDatabaseBuilder(context,
                RoomEventDatabase.class)
                .allowMainThreadQueries()
                .enableMultiInstanceInvalidation()
                .build();
        activeInstances.put(name, newInstance);
        return newInstance;
    }
}
